/**
 * Represents an error thrown when an operation is interrupted unexpectedly.
 * This custom error class extends the built-in Error class in JavaScript and
 * can be used to handle cases where a process or task is terminated before completion.
 */
export class InterruptError extends Error {
    constructor() {
        super(...arguments);
        this.name = 'InterruptError';
    }
}
/**
 * An error thrown when an action times out.
 */
export class TimeoutError extends Error {
    constructor() {
        super(...arguments);
        this.name = 'TimeoutError';
    }
}
/**
 * Represents an error thrown when an operation is aborted.
 */
export class AbortError extends Error {
    constructor() {
        super(...arguments);
        this.name = 'AbortError';
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi9zcmMvZXJyb3IvaW5kZXgudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7R0FJRztBQUNILE1BQU0sT0FBTyxjQUFlLFNBQVEsS0FBSztJQUF6Qzs7UUFDMkIsU0FBSSxHQUFHLGdCQUFnQixDQUFDO0lBQ25ELENBQUM7Q0FBQTtBQUVEOztHQUVHO0FBQ0gsTUFBTSxPQUFPLFlBQWEsU0FBUSxLQUFLO0lBQXZDOztRQUMyQixTQUFJLEdBQUcsY0FBYyxDQUFDO0lBQ2pELENBQUM7Q0FBQTtBQUVEOztHQUVHO0FBQ0gsTUFBTSxPQUFPLFVBQVcsU0FBUSxLQUFLO0lBQXJDOztRQUMyQixTQUFJLEdBQUcsWUFBWSxDQUFDO0lBQy9DLENBQUM7Q0FBQSJ9